### ISSUE TITLE
requesting Linux based native version

### ISSUE THREAD

**Issue by nort3x** [dcloudio/HBuilderX#2]
i tried this IDE and i liked it very much,
sadly there is no support for linux based systems, 
it's a Qt based application i would like to know whether or not there is going to be any support for linux

**Comment by FelipeAzambuja** [comment]
i need linux suport to

**Comment by qq824810885** [comment]
Linux is in our plan.

**Comment by tudorels** [comment]
Hello, I would also need the linux version. Is there an ETA? Thank you!

**Comment by alaarihan** [comment]
As you know, most of the developers prefer to use Linux so we are really want to have a lightweight alternative to VS Code to use in Linux.

**Comment by Youjin1985** [comment]
+1

**Comment by cpt-n3mo** [comment]
+1

**Comment by akirarika** [comment]
In fact, the official has given a Linux version based on wine. You can see it here (only in Chinese, temporarily)

[https://ask.dcloud.net.cn/article/37082](https://ask.dcloud.net.cn/article/37082)

Unfortunately, in this article, officials say they don't have the energy to provide a native version of Linux for the time being.

**Comment by nort3x** [comment]
don't expect me to use wine for this,
i can't find any reason why we are not getting native linux support beside personal preferences and this is discouraging
